gpu: drm: msm: Comment out tracing bit
error: implicit declaration of function 'trace_sde_evtlog' [-Werror,-Wimplicit-function-declaration]
  104 |         trace_sde_evtlog(name, line, log->data_cnt, log->data);
      |         ^
1 error generated.

Signed-off-by: shygosh <mossynine@gmail.com>
Signed-off-by: Yahya Wessam <yahyawessam2002@gmail.com>
(cherry picked from commit b0ba5b28ea5dc191478448efa0a98f9a9b31bd09)