qcacld-3.0: Fix implicit enum-enum-cast warnings
This fixes the following warning when building with newer clang:
error: implicit conversion from enumeration type
      'A_STATUS' to different enumeration type 'QDF_STATUS' [-Werror,-Wimplicit-enum-enum-cast]

Change-Id: I84f9f9b0406fad6df74749cbcb2cb176d42525aa
Signed-off-by: angelomds42 <angelomds42@gmail.com>
Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>

(cherry picked from commit d8aecea60236fd4b81615b18a4e1e95724b1f7c1)